apiVersion: jcrs.jcrs.dev/v1
kind: LeviathanBuild
metadata:
  labels:
    app.kubernetes.io/name: jobrunner
    app.kubernetes.io/managed-by: kustomize
  name: leviathanbuild-sample2
spec:
  packageName: testyMcTestFace2
  buildType: Build  # default
  sourceType: Local  # default
  sourcePath: "testPath2/path2"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello2
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
  
